<?php

return [
    'endpoint' => env('DATALAB_ENDPOINT', 'https://www.datalab.to/api/v1/'),
    'api_key' => env('DATALAB_API_KEY', ''),
    'marker_poll_interval_seconds' => (int) env('DATALAB_MARKER_POLL_INTERVAL_SECONDS', 5),
    'extraction_schema_poll_interval_seconds' => (int) env('DATALAB_EXTRACTION_SCHEMA_POLL_INTERVAL_SECONDS', 5),
    'form_filling_poll_interval_seconds' => (int) env('DATALAB_FORM_FILLING_POLL_INTERVAL_SECONDS', 5),
    'supported_files' => [
        'mimetypes' => [
            'application/pdf',
            'application/vnd.ms-excel',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'application/vnd.ms-excel.sheet.macroEnabled.12',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
            'text/csv',
            'application/vnd.oasis.opendocument.spreadsheet',
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/vnd.oasis.opendocument.text',
            'application/vnd.ms-powerpoint',
            'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            'application/vnd.oasis.opendocument.presentation',
            'text/html',
            'application/epub+zip',
            'image/png',
            'image/jpeg',
            'image/webp',
            'image/gif',
            'image/tiff',
        ],
        'extensions' => [
            'pdf',
            'xls',
            'xlsx',
            'xlsm',
            'xltx',
            'csv',
            'ods',
            'doc',
            'docx',
            'odt',
            'ppt',
            'pptx',
            'odp',
            'html',
            'epub',
            'png',
            'jpg',
            'jpeg',
            'webp',
            'gif',
            'tiff',
        ],
    ],
];
